version: '2'
services:
  ss-local:
    build: .
    volumes:
      - ./conf:/conf
    ports:
      - "8080:8118"
    entrypoint:
      - /bin/sh
    command: -c "apk --update add privoxy && sed -i'' 's/127\.0\.0\.1:8118/0\.0\.0\.0:8118/' /etc/privoxy/config && echo 'forward-socks5 / 127.0.0.1:1080 .' >> /etc/privoxy/config && privoxy /etc/privoxy/config && sslocal -c /conf/conf_client.json"
  ss-server:
    build: .
    volumes:
      - ./conf:/conf
    ports:
      - "6666:1234"
    entrypoint:
      - ssserver
    command: -c /conf/conf.json
